version: '3.8'

services:
  oet-mcp-server:
    build: .
    image: oet-mcp-server
    container_name: oet-mcp-server
    restart: unless-stopped
    environment:
      - MCP_PROXY_DEBUG=true
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.oet-mcp-freely-given.entrypoints: https
      traefik.http.routers.oet-mcp-freely-given.rule: Host(`mcp.freely-given.org`)
      traefik.http.routers.oet-mcp-freely-given.service: oet-mcp-freely-given
      traefik.http.routers.oet-mcp-freely-given.tls: true
      traefik.http.routers.oet-mcp-freely-given.tls.certresolver: cloudflare
      traefik.http.services.oet-mcp-freely-given.loadbalancer.server.port: 8080
      traefik.http.services.oet-mcp-freely-given.loadbalancer.server.scheme: http
      traefik.tls.stores.default.defaultgeneratedcert.resolver: cloudflare
      traefik.tls.stores.default.defaultgeneratedcert.domain.main: mcp.freely-given.org

networks:
  proxy:
    external: true
